### ISSUE TITLE
Uncaught Error: Unable to find node on an unmounted component. [After update to react 18]

### ISSUE THREAD

**Issue by foxhound87** [STRML/react-draggable#710]
I don't know why it is not working anymore, my code is very simple, but after updating to react 18 stopped working:

code: https://github.com/foxhound87/mobx-react-form-devtools/blob/master/src/components/Draggable.jsx#L11

Version: 4.4.5

these errors are appearing:

```
Uncaught Error: Unable to find node on an unmounted component.
    at findHostInstanceWithWarning (react-dom.development.js:24281:1)
    at Object.findDOMNode (react-dom.development.js:24804:1)
    at DraggableCore.findDOMNode (DraggableCore.js:389:1)
    at DraggableCore.componentDidMount (DraggableCore.js:352:1)
    at commitLayoutEffectOnFiber (react-dom.development.js:23305:1)
    at commitLayoutMountEffects_complete (react-dom.development.js:24688:1)
    at commitLayoutEffects_begin (react-dom.development.js:24674:1)
    at commitLayoutEffects (react-dom.development.js:24612:1)
    at commitRootImpl (react-dom.development.js:26823:1)
    at commitRoot (react-dom.development.js:26682:1)
```

```
react-dom.development.js:18687 The above error occurred in the <DraggableCore> component:

    at DraggableCore (http://localhost:8888/main.js:75147:5)
    at Draggable (http://localhost:8888/main.js:74645:5)
    at observerComponent (http://localhost:8888/main.js:40445:73)
    at div
    at div
    at div
    at div
    at Dock (http://localhost:8888/main.js:49158:5)
    at div
    at observerComponent (http://localhost:8888/main.js:40445:73)
    at UI
    at div
    at observerComponent (http://localhost:8888/main.js:169213:73)
```

```
The above error occurred in the <Draggable> component:

    at Draggable (http://localhost:8888/main.js:74645:5)
    at observerComponent (http://localhost:8888/main.js:40445:73)
    at div
    at div
    at div
    at div
    at Dock (http://localhost:8888/main.js:49158:5)
    at div
    at observerComponent (http://localhost:8888/main.js:40445:73)
    at UI
    at div
    at observerComponent (http://localhost:8888/main.js:169213:73)
```

```
react-dom.development.js:24281 Uncaught Error: Unable to find node on an unmounted component.
    at findHostInstanceWithWarning (react-dom.development.js:24281:1)
    at Object.findDOMNode (react-dom.development.js:24804:1)
    at DraggableCore.findDOMNode (DraggableCore.js:389:1)
    at DraggableCore.componentWillUnmount (DraggableCore.js:366:1)
    at callComponentWillUnmountWithTimer (react-dom.development.js:22852:1)
    at safelyCallComponentWillUnmount (react-dom.development.js:22873:1)
    at commitDeletionEffectsOnFiber (react-dom.development.js:24129:1)
    at recursivelyTraverseDeletionEffects (react-dom.development.js:23989:1)
    at commitDeletionEffectsOnFiber (react-dom.development.js:24133:1)
    at recursivelyTraverseDeletionEffects (react-dom.development.js:23989:1)
```

**Comment by saidheerajpaluvadi** [comment]
Yes, I'm also facing the same issue too!

**Comment by dolev146** [comment]
for me as well
