### ISSUE TITLE
error in react 19

### ISSUE THREAD

**Issue by daviderusso1984** [STRML/react-draggable#771]
Draggable.js:210 Uncaught TypeError: _reactDom.default.findDOMNode is not a function
    at Draggable.findDOMNode (Draggable.js:210:1)
    at Draggable.componentDidMount (Draggable.js:194:1)
    at react-stack-bottom-frame (react-dom-client.development.js:22451:1)
    at runWithFiberInDEV (react-dom-client.development.js:543:1)
    at commitLayoutEffectOnFiber (react-dom-client.development.js:11419:1)
    at recursivelyTraverseLayoutEffects (react-dom-client.development.js:12410:1)
    at commitLayoutEffectOnFiber (react-dom-client.development.js:11413:1)
    at recursivelyTraverseLayoutEffects (react-dom-client.development.js:12410:1)
    at commitLayoutEffectOnFiber (react-dom-client.development.js:11529:1)
    at recursivelyTraverseLayoutEffects (react-dom-client.development.js:12410:1)

**Comment by Mirott** [comment]
I have the same problem

**Comment by andreatiled** [comment]
A simple workaround is to provide a ref to a child element:

```js
<Draggable nodeRef={myRef}>
   <div ref={myRef} />
</Draggable>
```

**Comment by dtasev-ecmwf** [comment]
Unfortunately the fix above stopped working for some reason for me. For my simple use-case I realised that this dependency is likely an overkill when all the movement logic I need is:

```
const top = e.currentTarget.parentElement!.getBoundingClientRect().top;
e.currentTarget.parentElement!.style.top = top + e.movementY + 'px';
const left = e.currentTarget.parentElement!.getBoundingClientRect().left;
e.currentTarget.parentElement!.style.left = left + e.movementX + 'px';
```

essentially ending up with

```
const Draggable = memo(function (props: { children: any, position: { x: number, y: number }}) {
    const [dragging, setDragging] = useState(false);

    const moveWidget = useCallback((e: React.MouseEvent) => {
        if (dragging) {
            const top = e.currentTarget.parentElement!.getBoundingClientRect().top;
            e.currentTarget.parentElement!.style.top = top + e.movementY + 'px';
            const left = e.currentTarget.parentElement!.getBoundingClientRect().left;
            e.currentTarget.parentElement!.style.left = left + e.movementX + 'px';
        }
    }, [dragging]);

    return <div style={{ position: 'absolute', top: props.position.y, left: props.position.y }} >
        <div className="handle"
            onMouseDown={() => { console.log("dragging start"); setDragging(true) }}
            onMouseUp={() => { console.log("dragging stop"); setDragging(false) }}
            onMouseEnter={() => { console.log("dragging stop"); setDragging(false) }}
            onMouseMove={moveWidget}>
        </div>
        {props.children}
    </div>;
});
```
as a super basic drop-in.

**Comment by SValentyn** [comment]
Thanks [andreatiled](https://github.com/andreatiled)
The workaround above worked for me, but there were type conflicts, so I had to manually set the ref type.

in child component:
```ts
const CountryPopup = forwardRef<HTMLDivElement, CountryPopupProps>(({country}, ref) => {
    return (
        <Draggable
            nodeRef={ref as RefObject<HTMLElement>}
            allowAnyClick={true}
        >
            <div
                ref={ref}
                ...
```

in parent component:
```ts
...
const popupRef = useRef<HTMLDivElement>(null);
...
<CountryPopup ref={popupRef} country={currentCountry}/>
```

**Comment by siamahnaf** [comment]
very important package it is. React 19 support is required now. If anyone using alternative package please inform me?

**Comment by ellis** [comment]
Thanks @andreatiled !  That worked for me.
Like @SValentyn , I also had a type error, but I just cast it.

**Comment by galangel** [comment]
@andreatiled 
Thank you very much

**Comment by rhyek** [comment]
The `nodeRef` solution does not work when actually using React 19. More info [here](https://github.com/react-grid-layout/react-draggable/issues/779).

**Comment by Floryvibla** [comment]
> The `nodeRef` solution does not work when actually using React 19. More info [here](https://github.com/react-grid-layout/react-draggable/issues/779).

It works, you need to type it like @SValentyn  comment mentioned

**Comment by rhyek** [comment]
> > The `nodeRef` solution does not work when actually using React 19. More info [here](https://github.com/react-grid-layout/react-draggable/issues/779).
> 
> It works, you need to type it like @SValentyn  comment mentioned

It's not about types. Did you read the issue I linked?

**Comment by phongkien** [comment]
> > > The `nodeRef` solution does not work when actually using React 19. More info [here](https://github.com/react-grid-layout/react-draggable/issues/779).
> > 
> > 
> > It works, you need to type it like [@SValentyn](https://github.com/SValentyn)  comment mentioned
> 
> It's not about types. Did you read the issue I linked?

It does works, I think he meant "type" as in copying https://github.com/react-grid-layout/react-draggable/issues/771#issuecomment-2545737391 suggestion.

e.g.

```ts
import React, { useRef } from "react";
import Draggable from "react-draggable";

const ComponentTest: React.FC = () => {
  const nodeRef = useRef<any>(null);

  return (
    <Draggable nodeRef={nodeRef}>
      <div
        ref={nodeRef}<==============ref here is important
        style={
          {
            width: "400px",
            height: "200px",
            background: "green",
          }
        }
      >
        <div>Hello world</div>
      </div>
    </Draggable>
  );
};
```

**Comment by RM-Eric** [comment]
How would the ref work with the ResponsiveGridLayout component?

**Comment by LaxmanPache123** [comment]
> provide a ref to a child element:
> 
> <Draggable nodeRef={myRef}>

Thanks @andreatiled  its worked for me

**Comment by Smona** [comment]
Looks like this has been resolved as of 4.7.0 (probably in 4.6.0)! so this issue can likely be closed.

EDIT: this workaround may still be needed due to #670
